language: cpp

matrix:
  include:
    - os: linux
      dist: jammy
      sudo: true
      compiler: gcc

    - os: linux
      dist: jammy
      sudo: true
      compiler: clang

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make