language: cpp

matrix:
  include:
    - os: linux
      dist: jammy
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-11
        env:
          - MATRIX_EVAL="CC=gcc-11 CXX=g++-11"

    - os: linux
      dist: jammy
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - clang-14
      env:
        - MATRIX_EVAL="CC=clang-14 CXX=clang++-14"


before_install:
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - git checkout tags/v3.1.0
  - cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo env "PATH=$PATH" cmake --build build/ --target install
  - cd ..


script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make help
  - ls -la
  - ./unit_tests