language: cpp

matrix:
  include:
    - os: linux
      dist: jammy
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-11
        env:
          - MATRIX_EVAL="CC=gcc-11 CXX=g++-11"

    - os: linux
      dist: jammy
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - clang-14
      env:
        - MATRIX_EVAL="CC=clang-14 CXX=clang++-14"

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make