name: code analysis

on: [push, pull_request]

jobs:
  core-guidelines:
    name: core-guidelines-check
    runs-on: windows-2022

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-catch
        run: bash ./install_catch.sh

      - name: setup-cmake
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: cpp-core-guidelines-check
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        id: run-analysis
        with:
          ruleset: ${{ github.workspace }}/core-guidelines.ruleset
          cmakeBuildDirectory: ${{ github.workspace }}/build
          buildConfiguration: Release
          ignoredPaths: ${{ github.workspace }}/test

      - name: upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}


  clang-analyzer:
    name: clang-analyzer-checks
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - pkgs: clang-14 llvm-14-dev libclang-14-dev iwyu clang-tidy-14 clang-tools-14
            cxx: clang++-14

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      
      - name: setup-tools
        run: sudo apt install -y ${{ matrix.pkgs }}

      - name: setup-catch
        env:
          CXX: ${{ matrix.cxx }}
        run: sudo bash ./install_catch.sh

      - name: setup-cmake
        env:
          CXX: ${{ matrix.cxx }}
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu"
      
      - name: include-what-you-use
        run: cmake --build . > iwyu.out 2>&1
      
      - uses: actions/upload-artifact@v3
        with:
          name: iwyu-analysis-results
          path: ${{ github.workspace }}/build/iwyu.out