name: code analysis

on: [push, pull_request]

jobs:
  core-guidelines:
    name: core-guidelines-check
    runs-on: windows-2022

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-catch
        run: bash ./install_catch.sh

      - name: setup-cmake
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF

      - name: cpp-core-guidelines-check
        uses: microsoft/msvc-code-analysis-action@v0.1.1
        id: run-analysis
        with:
          ruleset: ${{ github.workspace }}/core-guidelines.ruleset
          cmakeBuildDirectory: ${{ github.workspace }}/build
          buildConfiguration: Release
          ignoredPaths: ${{ github.workspace }}/test

      - name: upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}


  clang-analyzers:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        tool: [ { name: iwyu, cmake-flag: CMAKE_CXX_INCLUDE_WHAT_YOU_USE="iwyu" },
                { name: clang-tidy, cmake-flag: CMAKE_CXX_CLANG_TIDY="clang-tidy" } ]
        include:
          - pkgs: clang-14 llvm-14-dev libclang-14-dev iwyu clang-tools-14 clang-tidy-14
            cxx: clang++-14

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.tool.name }}

    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      
      - name: setup-tools
        run: sudo apt install -y ${{ matrix.pkgs }}

      - name: setup-catch
        env:
          CXX: ${{ matrix.cxx }}
        run: sudo bash ./install_catch.sh

      - name: setup-analysis
        env:
          CXX: ${{ matrix.cxx }}
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -D${{ matrix.tool.cmake-flag }}
      
      - name: run-analysis
        run: cmake --build . 2>&1 | tee ${{ matrix.tool.name }}-out.txt
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.tool.name }}-analysis-results
          path: ${{ github.workspace }}/build/${{ matrix.tool.name }}-out.txt
