name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, RelWithDebInfo ]
        compiler: [
            #{ cxx: g++-12, pkgs: gcc@12 },
            { cxx: clang++, pkgs: llvm@15 }
        ]
        lib-type: [ { name: Static, cmake-flag: "OFF" }, { name: Shared, cmake-flag: "ON" } ]
        
    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.compiler.cxx }}, ${{ matrix.build-type }}, ${{ matrix.lib-type.name }}

    steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    - name: setup-compiler
      run: brew install cmake tbb ${{ matrix.compiler.pkgs }}

    - name: setup-catch
      env:
        CXX: ${{ matrix.compiler.cxx }}
      run: sudo bash ./install_catch.sh

    - name: setup-build
      env:
        CXX: ${{ matrix.compiler.cxx }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DGA_LINK_TBB=ON -DBUILD_SHARED_LIBS=${{ matrix.lib-type.cmake-flag }}

    - name: build
      run: cmake --build . --parallel
    
    - name: run-tests
      run: ctest --output-on-failure --schedule-random

    - name: install
      run: sudo cmake --install .
