name: sanitizers

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined, thread]
        include:
          - cxx: g++-11
            pkgs: gcc-11 libtbb-dev

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.cxx }} -fsanitize=${{ matrix.sanitizer }}

    steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    - name: setup-compiler
      run: sudo apt install -y ${{ matrix.pkgs }}

    - name: setup-catch
      env:
        CXX: ${{ matrix.cxx }}
      run: sudo bash ./install_catch.sh

    - name: setup-build
      env:
        CXX: ${{ matrix.cxx }}
      run: cmake .. -DGA_LINK_TBB=ON -DGA_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -g -fno-omit-frame-pointer"

    - name: build
      run: cmake --build . --parallel
    
    - name: run-tests
      run: ctest --output-on-failure --schedule-random