name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Debug, Release ]
        compiler: [ { cxx: cl, gen: "Visual Studio 17 2022" } ]
        lib-type: [ { name: Static, cmake-flag: "OFF" }, { name: Shared, cmake-flag: "ON" } ]

        #- cxx: g++
        #  pkgs: mingw --version=11.2.0
        #  gen: "Unix Makefiles"

        #- cxx: g++
        #  pkgs: mingw --version=12.2.0
        #  gen: "Unix Makefiles"

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.compiler.cxx }}, ${{ matrix.build-type }}, ${{ matrix.lib-type.name }}


    steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    #- name: setup-compiler
    #  run: choco install -y --allow-downgrade ${{ matrix.compiler.pkgs }}

    - name: setup-catch
      env:
        CXX: ${{ matrix.compiler.cxx }}
        CMAKE_GENERATOR: ${{ matrix.compiler.gen }}
      run: bash ./install_catch.sh

    - name: setup-build
      env:
        CXX: ${{ matrix.compiler.cxx }}
        CMAKE_GENERATOR: ${{ matrix.compiler.gen }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_SHARED_LIBS=${{ matrix.lib-type.cmake-flag }}

    - name: build
      run: cmake --build . --parallel --config ${{ matrix.build-type }}
    
    - name: run-tests
      run: ctest --output-on-failure --schedule-random

    - name: install
      run: cmake --install . --config ${{ matrix.build-type }}
